apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amir-fix-external-secret
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: amir-fix-externalsecrets
  data:
    - secretKey: token
      remoteRef:
        key: secret/amir-secrets
        property: pass
